// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: statechannel/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSendCoin struct {
	Creator           string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Sender            string      `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver          string      `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount            *types.Coin `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Unlockblockheight uint64      `protobuf:"varint,5,opt,name=unlockblockheight,proto3" json:"unlockblockheight,omitempty"`
}

func (m *MsgSendCoin) Reset()         { *m = MsgSendCoin{} }
func (m *MsgSendCoin) String() string { return proto.CompactTextString(m) }
func (*MsgSendCoin) ProtoMessage()    {}
func (*MsgSendCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_7387449a6db5c2d5, []int{0}
}
func (m *MsgSendCoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendCoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendCoin.Merge(m, src)
}
func (m *MsgSendCoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendCoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendCoin proto.InternalMessageInfo

func (m *MsgSendCoin) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendCoin) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSendCoin) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgSendCoin) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *MsgSendCoin) GetUnlockblockheight() uint64 {
	if m != nil {
		return m.Unlockblockheight
	}
	return 0
}

type MsgSendCoinResponse struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *MsgSendCoinResponse) Reset()         { *m = MsgSendCoinResponse{} }
func (m *MsgSendCoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendCoinResponse) ProtoMessage()    {}
func (*MsgSendCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7387449a6db5c2d5, []int{1}
}
func (m *MsgSendCoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendCoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendCoinResponse.Merge(m, src)
}
func (m *MsgSendCoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendCoinResponse proto.InternalMessageInfo

func (m *MsgSendCoinResponse) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type MsgWithdrawCoin struct {
	Index    string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Receiver string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (m *MsgWithdrawCoin) Reset()         { *m = MsgWithdrawCoin{} }
func (m *MsgWithdrawCoin) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawCoin) ProtoMessage()    {}
func (*MsgWithdrawCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_7387449a6db5c2d5, []int{2}
}
func (m *MsgWithdrawCoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawCoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawCoin.Merge(m, src)
}
func (m *MsgWithdrawCoin) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawCoin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawCoin proto.InternalMessageInfo

func (m *MsgWithdrawCoin) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgWithdrawCoin) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

type MsgWithdrawCoinResponse struct {
}

func (m *MsgWithdrawCoinResponse) Reset()         { *m = MsgWithdrawCoinResponse{} }
func (m *MsgWithdrawCoinResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawCoinResponse) ProtoMessage()    {}
func (*MsgWithdrawCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7387449a6db5c2d5, []int{3}
}
func (m *MsgWithdrawCoinResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawCoinResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawCoinResponse.Merge(m, src)
}
func (m *MsgWithdrawCoinResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawCoinResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSendCoin)(nil), "ttdung.statechannel.statechannel.MsgSendCoin")
	proto.RegisterType((*MsgSendCoinResponse)(nil), "ttdung.statechannel.statechannel.MsgSendCoinResponse")
	proto.RegisterType((*MsgWithdrawCoin)(nil), "ttdung.statechannel.statechannel.MsgWithdrawCoin")
	proto.RegisterType((*MsgWithdrawCoinResponse)(nil), "ttdung.statechannel.statechannel.MsgWithdrawCoinResponse")
}

func init() { proto.RegisterFile("statechannel/tx.proto", fileDescriptor_7387449a6db5c2d5) }

var fileDescriptor_7387449a6db5c2d5 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbb, 0x4e, 0xe3, 0x40,
	0x18, 0x85, 0x33, 0xb9, 0x6d, 0x76, 0xb2, 0xd2, 0x6a, 0x67, 0xb9, 0x38, 0x2e, 0x2c, 0xcb, 0x55,
	0x24, 0x60, 0x2c, 0x27, 0xa2, 0xa0, 0x25, 0xb5, 0x1b, 0x53, 0x20, 0xd1, 0xf9, 0xf2, 0xcb, 0xb6,
	0x48, 0x66, 0x2c, 0xcf, 0x38, 0x04, 0x89, 0x87, 0xe0, 0x81, 0x78, 0x00, 0xca, 0x94, 0x94, 0x28,
	0x79, 0x06, 0x7a, 0x14, 0xdb, 0x89, 0x6c, 0x40, 0x82, 0x34, 0x96, 0x8e, 0xce, 0x3f, 0xe7, 0x3f,
	0x9f, 0x67, 0xf0, 0xa1, 0x90, 0xae, 0x04, 0x3f, 0x72, 0x19, 0x83, 0xa9, 0x29, 0x17, 0x34, 0x49,
	0xb9, 0xe4, 0x44, 0x97, 0x32, 0xc8, 0x58, 0x48, 0xab, 0x6e, 0x4d, 0xa8, 0x9a, 0xcf, 0xc5, 0x8c,
	0x0b, 0xd3, 0x73, 0x05, 0x98, 0x73, 0xcb, 0x03, 0xe9, 0x5a, 0xa6, 0xcf, 0x63, 0x56, 0x24, 0x18,
	0x4f, 0x08, 0xf7, 0x6d, 0x11, 0x5e, 0x01, 0x0b, 0x26, 0x3c, 0x66, 0x44, 0xc1, 0xbf, 0xfc, 0x14,
	0x5c, 0xc9, 0x53, 0x05, 0xe9, 0x68, 0xf8, 0xdb, 0xd9, 0x4a, 0x72, 0x84, 0xbb, 0x02, 0x58, 0x00,
	0xa9, 0xd2, 0xcc, 0x8d, 0x52, 0x11, 0x15, 0xf7, 0x52, 0xf0, 0x21, 0x9e, 0x43, 0xaa, 0xb4, 0x72,
	0x67, 0xa7, 0x89, 0x85, 0xbb, 0xee, 0x8c, 0x67, 0x4c, 0x2a, 0x6d, 0x1d, 0x0d, 0xfb, 0xa3, 0x01,
	0x2d, 0xea, 0xd0, 0x4d, 0x1d, 0x5a, 0xd6, 0xa1, 0x9b, 0xc5, 0x4e, 0x39, 0x48, 0x4e, 0xf1, 0xbf,
	0x8c, 0x4d, 0xb9, 0x7f, 0xeb, 0x6d, 0x3e, 0x11, 0xc4, 0x61, 0x24, 0x95, 0x8e, 0x8e, 0x86, 0x6d,
	0xe7, 0xb3, 0x61, 0x9c, 0xe0, 0xff, 0x95, 0xf6, 0x0e, 0x88, 0x84, 0x33, 0x01, 0xe4, 0x00, 0x77,
	0x62, 0x16, 0xc0, 0xa2, 0x64, 0x28, 0x84, 0x31, 0xc1, 0x7f, 0x6d, 0x11, 0x5e, 0xc7, 0x32, 0x0a,
	0x52, 0xf7, 0x2e, 0xc7, 0xfd, 0x72, 0xb0, 0x86, 0xd4, 0xac, 0x23, 0x19, 0x03, 0x7c, 0xfc, 0x21,
	0x64, 0xbb, 0x75, 0xf4, 0x86, 0x70, 0xcb, 0x16, 0x21, 0x49, 0x70, 0x6f, 0xf7, 0x3f, 0xcf, 0xe8,
	0x77, 0x57, 0x44, 0x2b, 0x00, 0xea, 0xf9, 0x5e, 0xe3, 0x3b, 0xde, 0x07, 0xfc, 0xa7, 0x86, 0x65,
	0xfd, 0x28, 0xa6, 0x7a, 0x44, 0xbd, 0xd8, 0xfb, 0xc8, 0x76, 0xfb, 0xa5, 0xfd, 0xbc, 0xd2, 0xd0,
	0x72, 0xa5, 0xa1, 0xd7, 0x95, 0x86, 0x1e, 0xd7, 0x5a, 0x63, 0xb9, 0xd6, 0x1a, 0x2f, 0x6b, 0xad,
	0x71, 0x33, 0x0e, 0x63, 0x19, 0x65, 0x1e, 0xf5, 0xf9, 0xcc, 0x2c, 0xe2, 0xcd, 0xda, 0x43, 0x5e,
	0xd4, 0xa5, 0xbc, 0x4f, 0x40, 0x78, 0xdd, 0xfc, 0x65, 0x8e, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xd5, 0x0d, 0x23, 0x11, 0xf4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SendCoin(ctx context.Context, in *MsgSendCoin, opts ...grpc.CallOption) (*MsgSendCoinResponse, error)
	WithdrawCoin(ctx context.Context, in *MsgWithdrawCoin, opts ...grpc.CallOption) (*MsgWithdrawCoinResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendCoin(ctx context.Context, in *MsgSendCoin, opts ...grpc.CallOption) (*MsgSendCoinResponse, error) {
	out := new(MsgSendCoinResponse)
	err := c.cc.Invoke(ctx, "/ttdung.statechannel.statechannel.Msg/SendCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawCoin(ctx context.Context, in *MsgWithdrawCoin, opts ...grpc.CallOption) (*MsgWithdrawCoinResponse, error) {
	out := new(MsgWithdrawCoinResponse)
	err := c.cc.Invoke(ctx, "/ttdung.statechannel.statechannel.Msg/WithdrawCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SendCoin(context.Context, *MsgSendCoin) (*MsgSendCoinResponse, error)
	WithdrawCoin(context.Context, *MsgWithdrawCoin) (*MsgWithdrawCoinResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendCoin(ctx context.Context, req *MsgSendCoin) (*MsgSendCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCoin not implemented")
}
func (*UnimplementedMsgServer) WithdrawCoin(ctx context.Context, req *MsgWithdrawCoin) (*MsgWithdrawCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawCoin not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendCoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttdung.statechannel.statechannel.Msg/SendCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendCoin(ctx, req.(*MsgSendCoin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawCoin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ttdung.statechannel.statechannel.Msg/WithdrawCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawCoin(ctx, req.(*MsgWithdrawCoin))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ttdung.statechannel.statechannel.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCoin",
			Handler:    _Msg_SendCoin_Handler,
		},
		{
			MethodName: "WithdrawCoin",
			Handler:    _Msg_WithdrawCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statechannel/tx.proto",
}

func (m *MsgSendCoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendCoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendCoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Unlockblockheight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Unlockblockheight))
		i--
		dAtA[i] = 0x28
	}
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendCoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendCoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendCoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawCoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawCoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawCoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawCoinResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawCoinResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawCoinResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSendCoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Unlockblockheight != 0 {
		n += 1 + sovTx(uint64(m.Unlockblockheight))
	}
	return n
}

func (m *MsgSendCoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawCoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawCoinResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSendCoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendCoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendCoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unlockblockheight", wireType)
			}
			m.Unlockblockheight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Unlockblockheight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendCoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendCoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendCoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawCoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawCoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawCoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawCoinResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawCoinResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawCoinResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
